---
title: "p8105_yh3555_hw6"
author: "Yuchen Hua"
date: "2022-11-28"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(readr)
set.seed(1)
```


## Problem 2
Import data
```{r}
homicide = read.csv("./data./homicide-data.csv")
```

Date cleaning
```{r}
homicide_clean = homicide %>%
  mutate(city_state = str_c(city, ",", state)) %>%
  mutate(city_state = as.factor(city_state)) %>%
  mutate(victim_age = as.numeric(victim_age)) %>%
  group_by(city_state, disposition) %>% 
  filter(!city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL"),
         !victim_age %in% c(NA),
         !victim_sex %in% c("Unknown")) %>%
  filter(victim_race %in% c("Black", "White")) %>%
  mutate(resolved = ifelse(disposition %in% c("Closed by arrest"), 1, 0)) %>%
  select(-uid, -reported_date, -victim_last, -victim_first, -lat, -lon)
homicide_clean
```
If the case was closed by arrested, which was solved, it would be labelled as 1. If Open/No arrest or Closed without arrest, it would be labelled as 0. 

For Baltimore,MD
```{r}
baltimore_fit = homicide_clean %>%
  filter(city_state %in% c("Baltimore,MD")) %>%
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())
baltimore_fit
baltimore_tidy = broom::tidy(baltimore_fit)
```
The OR and CI of baltimore can be obtained. 
```{r}
baltimore_tidy %>%
  mutate(OR = exp(estimate),
         ci_lower = estimate + 1.96*std.error,
         ci_upper = estimate - 1.96*std.error) %>%
  select(term, log_OR = estimate, OR, p.value, ci_lower, ci_upper) %>%
  knitr::kable(digits = 3)
```


For all cities
```{r}
nest_city = homicide_clean %>%
  nest(data = -city_state) %>%
  mutate(
    models = map(data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data= ., family = binomial())),
    results = map(models, broom::tidy)) %>%
  select(-data, -models) %>%
  unnest(results) %>%
  filter(term != "(Intercept)") %>%
  select(city_state, term, estimate, std.error)
```

OR an CI
```{r}
nest_city %>%
   mutate(OR = exp(estimate),
         ci_lower = estimate + 1.96*std.error,
         ci_upper = estimate - 1.96*std.error) %>%
  select(term, log_OR = estimate, OR, ci_lower, ci_upper) %>%
  knitr::kable(digits = 3)
```


## Problem 3
Import data
```{r}
bw = read.csv("./data/birthweight.csv")
```





